repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        types:
          - python
        args:
          - --exclude=venv,./../old_code
          - --max-line-length=88
          - --ignore=E203,E501,W503
