name: __env
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - imageio=2.33.1
  - matplotlib=3.7.2
  - numpy-base=1.24.3
  - pillow=10.4.0
  - pip=24.0
  - pre-commit=3.4.0
  - python=3.8.19
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - pip:
      - keras==2.10.0
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-probability==0.16.0
